[default]
description = "Default permissions for the multiline-menubar plugin"
permissions = ["allow-create", "allow-remove", "allow-set-text", "allow-set-font-sizes", "allow-set-layout", "allow-set-tooltip", "allow-set-visible", "allow-set-menu", "allow-remove-menu", "allow-set-colors", "allow-set-bold", "allow-rect", "allow-set-popup-window", "allow-set-auto-popup", "allow-open-popup", "allow-close-popup", "allow-toggle-popup", "allow-is-visible"]
